apiVersion: apps/v1
kind: Deployment
metadata:
 name: my-flask-app-deployment # name of the deployment
 
spec:
 template: # pod defintion
   metadata:
     name: my-flask-app # name of the pod
     labels:
       app: my-flask-app
       tier: frontend
   spec:
     containers:
       - name: my-flask-app
         image: nathan14224/my-flask-app:latest
 replicas: 2
 selector: # Mandatory, Select the pods which needs to be in the replicaset
   matchLabels:
     app: my-flask-app
     tier: frontend


